project_id = "vnunsjoglkzbbdklcyii"

[functions.analyze-room]
verify_jwt = true

[functions.ai-assistant]
verify_jwt = true

[functions.search]
verify_jwt = false

[functions.score-startup]
verify_jwt = true
